name: test cicd

on:
  push:
  pull_request:
    branches: ["_.//"]
  workflow_dispatch:

env:
  test: "test"

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - id: echo
        run: |
          echo "Hello World
